# Generated by Django 3.2 on 2022-10-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='name_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.class'),
        ),
    ]
